export const movies = [
    {
        title: "KungFu Panda",
        img: "panda.jpg",
        year: "2024",
        cast: "Panda, Duck, Pig",
        genre: "Adventure",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Awesome",
        duration: "2hr 30m",
        grouping: "Trending"
    },
    {
        title: "The Marvel",
        img: "marvel.jpg",
        year: "2023",
        cast: "Captain marvel",
        genre: "Adventure, Action",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Positive",
        duration: "1hr 20m",
        grouping: "Trending"
    },
    {
        title: "A Quite Place",
        img: "quite.jpg",
        year: "2022",
        cast: "Aliens",
        genre: "Adventure, Aliens, Scifi",
        rating: 13,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Scary",
        duration: "1hr 30m",
        grouping: "Trending"
    },
    {
        title: "Spider-man",
        img: "spider.jpg",
        year: "2020",
        cast: "Spider, Andrew, Tom Holand",
        genre: "Adventure, Scifi, Fantasy",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Love",
        duration: "2hr 30m",
        grouping: "Trending"
    },
    {
        title: "Iron Man",
        img: "iron.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Brave",
        img: "brave.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Thor",
        img: "thor.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Inside Out",
        img: "inside.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Justice League",
        img: "justice.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Loki",
        img: "loki.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Scale",
        img: "scale.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Godzilla",
        img: "godzilla.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Cinderella",
        img: "cinderella.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Beauty and the Beast",
        img: "beauty.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Queen of Tears",
        img: "bannerMovie.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure, Scifi, Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
]