export const movies = [
    {
        title: "KungFu Panda",
        img: "panda.jpg",
        year: "2024",
        cast: "Panda, Duck, Pig",
        genre: "Action",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Awesome",
        duration: "2hr 30m",
        grouping: "Trending"
    },
    {
        title: "The Marvel",
        img: "marvel.jpg",
        year: "2023",
        cast: "Captain marvel",
        genre: "Action",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Positive",
        duration: "1hr 20m",
        grouping: "Trending"
    },
    {
        title: "A Quite Place",
        img: "quite.jpg",
        year: "2022",
        cast: "Aliens",
        genre: "Scifi",
        rating: 13,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Scary",
        duration: "1hr 30m",
        grouping: "Trending"
    },
    {
        title: "Spider-man",
        img: "spider.jpg",
        year: "2020",
        cast: "Spider, Andrew, Tom Holand",
        genre: "Scifi",
        rating: 10,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Love",
        duration: "2hr 30m",
        grouping: "Trending"
    },
    {
        title: "Iron Man",
        img: "iron.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Action",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Brave",
        img: "brave.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Thor",
        img: "thor.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Trending"
    },
    {
        title: "Inside Out",
        img: "inside.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Justice League",
        img: "justice.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Scifi",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Loki",
        img: "loki.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Scale",
        img: "scale.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Godzilla",
        img: "godzilla.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Cinderella",
        img: "cinderella.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Beauty and the Beast",
        img: "beauty.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Fantasy",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
    {
        title: "Queen of Tears",
        img: "bannerMovie.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Asian"
    },
]


    export const topmovies = [
       /* Top 10 Movies */
    {
        title: "Queen of Tears",
        img: "top1.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "1.png"
    },
    {
        title: "Kaiju No.8",
        img: "top2.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Action",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "2.png"
    },
    {
        title: "Twilight",
        img: "top3.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Scifi",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "3.png"
    },
    {
        title: "Parasyte the Gray",
        img: "top4.jpg",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Thriller",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "4.png"
    },
    {
        title: "Haiku",
        img: "top5.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Adventure",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "5.png"
    },
    {
        title: "Can't Buy Me Love",
        img: "top6.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "6.png"
    },
    {
        title: "It's Okay To Not Be Okay",
        img: "top7.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "7.png"
    },
    {
        title: "Start-Up",
        img: "top8.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Romantic",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "8.png"
    },
    {
        title: "Aquaman",
        img: "top9.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Scifi",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "9.png"
    },
    {
        title: "Exhuma",
        img: "top10.webp",
        year: "2005",
        cast: "Ironman, spiderman, hulk",
        genre: "Thriller",
        rating: 15,
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deleniti necessitatibus tempore vitae veritatis sequi est!",
        type: "Assemble",
        duration: "1hr 59m",
        grouping: "Top",
        number: "10.png"
    },
 
]

    



